import {
  Banknote,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Boxes,
  FileSpreadsheet,
  FileText,
  Landmark,
  LayoutDashboard,
  Package,
  Receipt,
  Scale,
  ScrollText,
  Settings,
  ShoppingCart,
  Truck,
  Users,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

export const SHELL_NAV_ICONS: Record<string, LucideIcon> = {
  home: LayoutDashboard,
  clients: Users,
  requests: FileText,
  proposals: ScrollText,
  'purchase-orders': ShoppingCart,
  catalog: BookOpen,
  assets: Package,
  fleet: Truck,
  alerts: Bell,
  billing: Receipt,
  'finance-overview': Wallet,
  'finance-receivables': Banknote,
  'finance-payables': Landmark,
  'finance-treasury': Wallet,
  'finance-reconciliation': Scale,
  'finance-expenses': Receipt,
  'finance-budgets': BarChart3,
  'finance-forecast': Wallet,
  'fiscal-documents': FileSpreadsheet,
  'fiscal-apuracao': FileText,
  'fiscal-tributos': ScrollText,
  'fiscal-periods': FileSpreadsheet,
  'fiscal-assessments': Scale,
  'accounting-chart': BookMarked,
  'accounting-journals': BookOpen,
  'accounting-diario': BookOpen,
  'accounting-razao': BookMarked,
  'accounting-balancete': BarChart3,
  'accounting-dre': FileSpreadsheet,
  'accounting-balanco': Landmark,
  'accounting-fechamentos': Scale,
  'accounting-fixed-assets': Landmark,
  suppliers: Users,
  procurement: ShoppingCart,
  inventory: Boxes,
  payroll: Users,
  reports: BarChart3,
  'operational-profitability': BarChart3,
  platform: Settings,
};

export function resolveNavIcon(itemId: string): LucideIcon {
  return SHELL_NAV_ICONS[itemId] ?? LayoutDashboard;
}
