export const SECURITY_AUDIT_ACTIONS = {
  AuthLogin: 'security:auth:login',
  AuthLoginFailure: 'security:auth:login_failure',
  AuthLogout: 'security:auth:logout',
  AuthLogoutAll: 'security:auth:logout_all',
  AuthRefreshReuse: 'security:auth:refresh_reuse',
  AuthSessionRevoked: 'security:auth:session_revoked',
  AuthzGrantCreate: 'security:authz:grant_create',
  AuthzGrantRevoke: 'security:authz:grant_revoke',
  ApprovalMatrixCreate: 'security:authz:approval-matrix:create',
  ApprovalMatrixPublish: 'security:authz:approval-matrix:publish',
  ApprovalRoleAssign: 'security:authz:approval-role:assign',
  AuthzDenied: 'security:authz:denied',
  AppBootstrap: 'security:app:bootstrap',
  ClientCreate: 'security:client:create',
  ClientUpdate: 'security:client:update',
  ClientDeactivate: 'security:client:deactivate',
  ClientActivate: 'security:client:activate',
  PeoplePersonCreate: 'security:people:person:create',
  PeoplePersonUpdate: 'security:people:person:update',
  PeoplePersonDeactivate: 'security:people:person:deactivate',
  PeoplePersonActivate: 'security:people:person:activate',
  IssuerLegalEntityCreate: 'security:issuer:legal-entity:create',
  IssuerLegalEntityUpdate: 'security:issuer:legal-entity:update',
  IssuerLegalEntityDeactivate: 'security:issuer:legal-entity:deactivate',
  IssuerLegalEntityActivate: 'security:issuer:legal-entity:activate',
  IssuerEstablishmentCreate: 'security:issuer:establishment:create',
  IssuerEstablishmentUpdate: 'security:issuer:establishment:update',
  IssuerEstablishmentDeactivate: 'security:issuer:establishment:deactivate',
  IssuerEstablishmentActivate: 'security:issuer:establishment:activate',
  IssuerTaxRegistrationCreate: 'security:issuer:tax-registration:create',
  IssuerTaxRegistrationUpdate: 'security:issuer:tax-registration:update',
  IssuerTaxRegistrationDeactivate: 'security:issuer:tax-registration:deactivate',
  IssuerTaxRegistrationActivate: 'security:issuer:tax-registration:activate',
  IssuerCertificateCreate: 'security:issuer:certificate:create',
  IssuerCertificateUpdate: 'security:issuer:certificate:update',
  IssuerCertificateDeactivate: 'security:issuer:certificate:deactivate',
  CatalogServiceCreate: 'security:catalog:service:create',
  CatalogServiceUpdateDraft: 'security:catalog:service:update-draft',
  CatalogServiceCreateVersion: 'security:catalog:service:create-version',
  CatalogServicePublish: 'security:catalog:service:publish',
  CatalogServiceDeactivate: 'security:catalog:service:deactivate',
  CatalogServiceActivate: 'security:catalog:service:activate',
  CatalogUnitCreate: 'security:catalog:unit:create',
  CatalogUnitUpdate: 'security:catalog:unit:update',
  CatalogUnitDeactivate: 'security:catalog:unit:deactivate',
  CatalogUnitActivate: 'security:catalog:unit:activate',
  ResourcesResourceTypeCreate: 'security:resources:resource-type:create',
  ResourcesResourceTypeUpdate: 'security:resources:resource-type:update',
  ResourcesResourceTypeDeactivate: 'security:resources:resource-type:deactivate',
  ResourcesResourceTypeActivate: 'security:resources:resource-type:activate',
  ResourcesLaborTypeCreate: 'security:resources:labor-type:create',
  ResourcesLaborTypeUpdate: 'security:resources:labor-type:update',
  ResourcesLaborTypeDeactivate: 'security:resources:labor-type:deactivate',
  ResourcesLaborTypeActivate: 'security:resources:labor-type:activate',
  ResourcesAssetCreate: 'security:resources:asset:create',
  ResourcesAssetUpdate: 'security:resources:asset:update',
  ResourcesAssetDeactivate: 'security:resources:asset:deactivate',
  ResourcesAssetActivate: 'security:resources:asset:activate',
  DocumentsDocumentCreate: 'security:documents:document:create',
  DocumentsDocumentUploadVersion: 'security:documents:document:upload-version',
  DocumentsDocumentDownload: 'security:documents:document:download',
  CommercialProposalCreate: 'security:commercial:proposal:create',
  CommercialProposalCreateVersion: 'security:commercial:proposal:create-version',
  CommercialProposalIssue: 'security:commercial:proposal:issue',
  CommercialProposalAccept: 'security:commercial:proposal:accept',
  CommercialProposalReject: 'security:commercial:proposal:reject',
  CommercialProposalExpire: 'security:commercial:proposal:expire',
  CommercialProposalCancel: 'security:commercial:proposal:cancel',
  CommercialPurchaseOrderCreate: 'security:commercial:purchase-order:create',
  CommercialPurchaseOrderRegister: 'security:commercial:purchase-order:register',
  CommercialPurchaseOrderCancel: 'security:commercial:purchase-order:cancel',
  CommercialPurchaseOrderAuthorizeOverrun: 'security:commercial:purchase-order:authorize-overrun',
  CommercialContractCreate: 'security:commercial:contract:create',
  CommercialContractUpdate: 'security:commercial:contract:update',
  CommercialContractActivate: 'security:commercial:contract:activate',
  CommercialContractClose: 'security:commercial:contract:close',
  CommercialContractExpire: 'security:commercial:contract:expire',
  RequestsServiceRequestCreate: 'security:requests:service-request:create',
  RequestsServiceRequestSubmit: 'security:requests:service-request:submit',
  RequestsServiceRequestReview: 'security:requests:service-request:review',
  RequestsServiceRequestApprove: 'security:requests:service-request:approve',
  RequestsServiceRequestReject: 'security:requests:service-request:reject',
  RequestsServiceRequestCancel: 'security:requests:service-request:cancel',
  RequestsServiceRequestConvert: 'security:requests:service-request:convert',
  ServiceOrdersServiceOrderCreate: 'security:service-orders:service-order:create',
  ServiceOrdersServiceOrderUpdate: 'security:service-orders:service-order:update',
  ServiceOrdersServiceOrderPrepare: 'security:service-orders:service-order:prepare',
  ServiceOrdersServiceOrderRelease: 'security:service-orders:service-order:release',
  ServiceOrdersServiceOrderCancel: 'security:service-orders:service-order:cancel',
  ServiceOrdersServiceOrderReopen: 'security:service-orders:service-order:reopen',
  ServiceOrdersPlannedResourcePlan: 'security:service-orders:planned-resource:plan',
  ServiceOrdersPlannedResourceRemove: 'security:service-orders:planned-resource:remove',
  ServiceOrdersResourceAllocate: 'security:service-orders:resource-allocation:allocate',
  ServiceOrdersResourceReallocate: 'security:service-orders:resource-allocation:reallocate',
  ServiceOrdersResourceRemoveAllocation: 'security:service-orders:resource-allocation:remove',
  ServiceOrdersExecutionStart: 'security:service-orders:execution:start',
  ServiceOrdersExecutionPause: 'security:service-orders:execution:pause',
  ServiceOrdersExecutionResume: 'security:service-orders:execution:resume',
  ServiceOrdersExecutionComplete: 'security:service-orders:execution:complete',
  ServiceOrdersExecutionRecord: 'security:service-orders:execution:record',
  ServiceOrdersOperationalCostRecord: 'security:service-orders:operational-cost:record',
  MeasurementsMeasurementCreate: 'security:measurements:measurement:create',
  MeasurementsMeasurementUpdate: 'security:measurements:measurement:update',
  MeasurementsMeasurementSubmit: 'security:measurements:measurement:submit',
  MeasurementsMeasurementReview: 'security:measurements:measurement:review',
  MeasurementsMeasurementApprove: 'security:measurements:measurement:approve',
  MeasurementsMeasurementReject: 'security:measurements:measurement:reject',
  BillingBillingRecordPrepare: 'security:billing:billing-record:prepare',
  BillingBillingRecordRead: 'security:billing:billing-record:read',
  BillingBillingRecordVoid: 'security:billing:billing-record:void',
  BillingBillingDocumentIssue: 'security:billing:billing-document:issue',
  BillingBillingDocumentRead: 'security:billing:billing-document:read',
  BillingBillingDocumentCancel: 'security:billing:billing-document:cancel',
  BillingBillingDocumentReplace: 'security:billing:billing-document:replace',
  BillingBillingDocumentDownload: 'security:billing:billing-document:download',
  FinanceReceivableOpen: 'security:finance:receivable:open',
  FinanceReceivableSettle: 'security:finance:receivable:settle',
  FinanceReceivableSettlementReverse: 'security:finance:receivable:settlement:reverse',
  FinanceReceivableCancel: 'security:finance:receivable:cancel',
  FinanceReceivableRead: 'security:finance:receivable:read',
  FinancePayableOpen: 'security:finance:payable:open',
  FinancePayablePay: 'security:finance:payable:pay',
  FinancePayableCancel: 'security:finance:payable:cancel',
  FinancePayableReverse: 'security:finance:payable:reverse',
  FinancePayableRead: 'security:finance:payable:read',
  FinanceExpenseCategoryCreate: 'security:finance:expense-category:create',
  FinanceExpenseCreate: 'security:finance:expense:create',
  FinanceExpenseSubmit: 'security:finance:expense:submit',
  FinanceExpenseApprove: 'security:finance:expense:approve',
  FinanceExpenseReject: 'security:finance:expense:reject',
  FinanceCollectionOpen: 'security:finance:collection:open',
  FinanceCollectionRead: 'security:finance:collection:read',
  FinanceCollectionActionCreate: 'security:finance:collection:action-create',
  FinanceCollectionPromiseCreate: 'security:finance:collection:promise-create',
  FinanceCollectionRenegotiate: 'security:finance:collection:renegotiate',
  FinanceTreasuryAccountOpen: 'security:finance:treasury:account-open',
  FinanceTreasuryPost: 'security:finance:treasury:post',
  FinanceTreasuryTransfer: 'security:finance:treasury:transfer',
  FinanceTreasuryReverse: 'security:finance:treasury:reverse',
  FinanceBankStatementImport: 'security:finance:bank-statement:import',
  FinanceReconciliationConfirm: 'security:finance:reconciliation:confirm',
  FinanceReconciliationUnreconcile: 'security:finance:reconciliation:unreconcile',
  FinanceBudgetCreate: 'security:finance:budget:create',
  FinanceBudgetApprove: 'security:finance:budget:approve',
  FinanceBudgetVersion: 'security:finance:budget:version',
  SupplierCreate: 'security:supplier:create',
  SupplierUpdate: 'security:supplier:update',
  SupplierDeactivate: 'security:supplier:deactivate',
  SupplierActivate: 'security:supplier:activate',
  ProcurementRequestCreate: 'security:procurement:request:create',
  ProcurementRequestSubmit: 'security:procurement:request:submit',
  ProcurementRequestApprove: 'security:procurement:request:approve',
  ProcurementRequestReject: 'security:procurement:request:reject',
  ProcurementRequestCancel: 'security:procurement:request:cancel',
  ProcurementOrderIssue: 'security:procurement:order:issue',
  ProcurementOrderReceive: 'security:procurement:order:receive',
  ProcurementOrderCancel: 'security:procurement:order:cancel',
  ProcurementInvoiceCreate: 'security:procurement:invoice:create',
  ProcurementInvoiceValidate: 'security:procurement:invoice:validate',
  ProcurementMatchCompute: 'security:procurement:match:compute',
  AccountingChartManage: 'security:accounting:chart:manage',
  AccountingPeriodOpen: 'security:accounting:period:open',
  AccountingPeriodClose: 'security:accounting:period:close',
  AccountingPeriodReopen: 'security:accounting:period:reopen',
  AccountingJournalDraft: 'security:accounting:journal:draft',
  AccountingJournalPost: 'security:accounting:journal:post',
  AccountingJournalReverse: 'security:accounting:journal:reverse',
  AccountingPostingRuleManage: 'security:accounting:posting-rule:manage',
  AccountingPostingRulePublish: 'security:accounting:posting-rule:publish',
  AccountingPostingRequest: 'security:accounting:posting-request:create',
  AccountingFixedAssetRegister: 'security:accounting:fixed-asset:register',
  AccountingFixedAssetAcquire: 'security:accounting:fixed-asset:acquire',
  AccountingFixedAssetDispose: 'security:accounting:fixed-asset:dispose',
  AccountingFixedAssetTransfer: 'security:accounting:fixed-asset:transfer',
  AccountingFixedAssetReverse: 'security:accounting:fixed-asset:reverse',
  FiscalDocumentDraft: 'security:fiscal:document:draft',
  FiscalDocumentAuthorize: 'security:fiscal:document:authorize',
  FiscalDocumentCancel: 'security:fiscal:document:cancel',
  FiscalTaxRulePublish: 'security:fiscal:tax-rule:publish',
  FiscalTaxCalculate: 'security:fiscal:tax:calculate',
  FiscalTaxAssessmentCreate: 'security:fiscal:tax-assessment:create',
  FiscalTaxAssessmentFinalize: 'security:fiscal:tax-assessment:finalize',
  FiscalTaxAssessmentAdjust: 'security:fiscal:tax-assessment:adjust',
  FiscalTaxAssessmentCancel: 'security:fiscal:tax-assessment:cancel',
  FiscalTaxAssessmentRead: 'security:fiscal:tax-assessment:read',
  FiscalPeriodOpen: 'security:fiscal:period:open',
  FiscalPeriodClose: 'security:fiscal:period:close',
  FiscalPeriodReopen: 'security:fiscal:period:reopen',
  FiscalPeriodRead: 'security:fiscal:period:read',
  InventoryMove: 'security:inventory:move',
  InventoryCostingRulePublish: 'security:inventory:costing-rule:publish',
  PayrollEventRecord: 'security:payroll:event-record',
  PayrollCalculate: 'security:payroll:calculate',
  PayrollPeriodClose: 'security:payroll:period-close',
  PayrollPeriodReopen: 'security:payroll:period-reopen',
  ReportsExportGenerate: 'security:reports:export:generate',
  AccessAdminRoleCreate: 'security:authz:access-role:create',
  AccessAdminRoleUpdate: 'security:authz:access-role:update',
  AccessAdminRoleActivate: 'security:authz:access-role:activate',
  AccessAdminRoleDeactivate: 'security:authz:access-role:deactivate',
  AccessAdminAssign: 'security:authz:access-assignment:assign',
  AccessAdminAssignmentRevoke: 'security:authz:access-assignment:revoke',
} as const;

export type SecurityAuditAction =
  (typeof SECURITY_AUDIT_ACTIONS)[keyof typeof SECURITY_AUDIT_ACTIONS];

export const SECURITY_AUDIT_CLASSIFICATIONS = {
  Critical: 'SECURITY_CRITICAL',
  Standard: 'SECURITY_STANDARD',
} as const;

export type SecurityAuditClassification =
  (typeof SECURITY_AUDIT_CLASSIFICATIONS)[keyof typeof SECURITY_AUDIT_CLASSIFICATIONS];

export const SECURITY_AUDIT_OUTCOMES = {
  Success: 'SUCCESS',
  Failure: 'FAILURE',
  Denied: 'DENIED',
} as const;

export type SecurityAuditOutcome =
  (typeof SECURITY_AUDIT_OUTCOMES)[keyof typeof SECURITY_AUDIT_OUTCOMES];

export const SECURITY_AUDIT_RESOURCE_TYPES = {
  Identity: 'security:identity',
  Session: 'security:session',
  Grant: 'security:grant',
  ApprovalMatrix: 'security:approval-matrix',
  AuthzDecision: 'security:authz-decision',
  Application: 'security:application',
  Client: 'security:client',
  PeoplePerson: 'security:people:person',
  IssuerLegalEntity: 'security:issuer:legal-entity',
  IssuerEstablishment: 'security:issuer:establishment',
  IssuerTaxRegistration: 'security:issuer:tax-registration',
  IssuerCertificate: 'security:issuer:certificate',
  CatalogService: 'security:catalog:service',
  CatalogUnit: 'security:catalog:unit',
  ResourcesResourceType: 'security:resources:resource-type',
  ResourcesLaborType: 'security:resources:labor-type',
  ResourcesAsset: 'security:resources:asset',
  DocumentsDocument: 'security:documents:document',
  CommercialProposal: 'security:commercial:proposal',
  CommercialPurchaseOrder: 'security:commercial:purchase-order',
  CommercialContract: 'security:commercial:contract',
  RequestsServiceRequest: 'security:requests:service-request',
  ServiceOrdersServiceOrder: 'security:service-orders:service-order',
  FinanceReceivable: 'security:finance:receivable',
  FinancePayable: 'security:finance:payable',
  FinanceExpense: 'security:finance:expense',
  FinanceCollection: 'security:finance:collection',
  FinanceTreasury: 'security:finance:treasury',
  FinanceBudget: 'security:finance:budget',
  Supplier: 'security:supplier',
  Procurement: 'security:procurement',
  AccountingLedger: 'security:accounting:ledger',
  FiscalDocument: 'security:fiscal:document',
  FiscalTaxEngine: 'security:fiscal:tax-engine',
  FiscalPeriod: 'security:fiscal:period',
  InventoryStock: 'security:inventory:stock',
  PayrollLedger: 'security:payroll:ledger',
  ReportsExport: 'security:reports:export',
  AccessRole: 'security:access-role',
  AccessAssignment: 'security:access-assignment',
} as const;

export type SecurityAuditResourceType =
  (typeof SECURITY_AUDIT_RESOURCE_TYPES)[keyof typeof SECURITY_AUDIT_RESOURCE_TYPES];

export type RecordSecurityAuditInput = {
  actorIdentityId?: string | null;
  actorSessionId?: string | null;
  action: SecurityAuditAction;
  resourceType: SecurityAuditResourceType;
  resourceId?: string | null;
  outcome: SecurityAuditOutcome;
  scopeType?: string | null;
  correlationId?: string | null;
  reasonCode?: string | null;
  classification: SecurityAuditClassification;
  metadata?: Record<string, unknown>;
};

export type SecurityAuditEventRow = {
  id: string;
  occurred_at: string;
  actor_identity_id: string | null;
  actor_session_id: string | null;
  action: string;
  resource_type: string;
  resource_id: string | null;
  outcome: SecurityAuditOutcome;
  scope_type: string | null;
  correlation_id: string | null;
  reason_code: string | null;
  classification: SecurityAuditClassification;
  metadata: Record<string, unknown>;
};
